---
deployment:
  tasks:
    - "/bin/bash -c 'export HOME=/home/jacobspl; cd /home/jacobspl/repositories/indkob; /usr/local/bin/npm install --production'"
    - "/bin/mkdir -p /home/jacobspl/repositories/indkob/data"
