// Kør én gang på serveren: node server/seed.js
// Indsætter ~1000 almindelige danske supermarkedsvarer i produktkataloget.
// INSERT OR IGNORE — springer eksisterende over.

const { DatabaseSync } = require('node:sqlite');
const path = require('path');
const fs   = require('fs');

const dataDir = process.env.DB_DIR || path.join(__dirname, '../data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'indkob.db'));
db.exec('PRAGMA foreign_keys = ON');

const products = [

  // ── Frugt & Grønt ──────────────────────────────────────────────────
  ['Æble', 'stk', 'Frugt & Grønt'],
  ['Pære', 'stk', 'Frugt & Grønt'],
  ['Banan', 'stk', 'Frugt & Grønt'],
  ['Appelsin', 'stk', 'Frugt & Grønt'],
  ['Citron', 'stk', 'Frugt & Grønt'],
  ['Lime', 'stk', 'Frugt & Grønt'],
  ['Mandarin', 'stk', 'Frugt & Grønt'],
  ['Grapefrugt', 'stk', 'Frugt & Grønt'],
  ['Mango', 'stk', 'Frugt & Grønt'],
  ['Ananas', 'stk', 'Frugt & Grønt'],
  ['Melon', 'stk', 'Frugt & Grønt'],
  ['Vandmelon', 'stk', 'Frugt & Grønt'],
  ['Druer, røde', 'kg', 'Frugt & Grønt'],
  ['Druer, hvide', 'kg', 'Frugt & Grønt'],
  ['Jordbær', 'bakke', 'Frugt & Grønt'],
  ['Blåbær', 'bakke', 'Frugt & Grønt'],
  ['Hindbær', 'bakke', 'Frugt & Grønt'],
  ['Brombær', 'bakke', 'Frugt & Grønt'],
  ['Kirsebær', 'bakke', 'Frugt & Grønt'],
  ['Fersken', 'stk', 'Frugt & Grønt'],
  ['Nektarin', 'stk', 'Frugt & Grønt'],
  ['Blomme', 'stk', 'Frugt & Grønt'],
  ['Avocado', 'stk', 'Frugt & Grønt'],
  ['Kiwi', 'stk', 'Frugt & Grønt'],
  ['Papaya', 'stk', 'Frugt & Grønt'],
  ['Kokosnød', 'stk', 'Frugt & Grønt'],
  ['Passionsfrugt', 'stk', 'Frugt & Grønt'],
  ['Tomat', 'stk', 'Frugt & Grønt'],
  ['Cherrytomater', 'bakke', 'Frugt & Grønt'],
  ['Blommetomater', 'stk', 'Frugt & Grønt'],
  ['Agurk', 'stk', 'Frugt & Grønt'],
  ['Squash', 'stk', 'Frugt & Grønt'],
  ['Aubergine', 'stk', 'Frugt & Grønt'],
  ['Peberfrugt, rød', 'stk', 'Frugt & Grønt'],
  ['Peberfrugt, gul', 'stk', 'Frugt & Grønt'],
  ['Peberfrugt, grøn', 'stk', 'Frugt & Grønt'],
  ['Løg', 'stk', 'Frugt & Grønt'],
  ['Rødløg', 'stk', 'Frugt & Grønt'],
  ['Forårsløg', 'bundt', 'Frugt & Grønt'],
  ['Hvidløg', 'stk', 'Frugt & Grønt'],
  ['Purreløg', 'stk', 'Frugt & Grønt'],
  ['Skalotteløg', 'stk', 'Frugt & Grønt'],
  ['Kartofler', 'kg', 'Frugt & Grønt'],
  ['Søde kartofler', 'stk', 'Frugt & Grønt'],
  ['Gulerødder', 'kg', 'Frugt & Grønt'],
  ['Pastinakker', 'stk', 'Frugt & Grønt'],
  ['Persillerod', 'stk', 'Frugt & Grønt'],
  ['Sellerirod', 'stk', 'Frugt & Grønt'],
  ['Rødbede', 'stk', 'Frugt & Grønt'],
  ['Radiser', 'bundt', 'Frugt & Grønt'],
  ['Rucola', 'pose', 'Frugt & Grønt'],
  ['Spinat', 'pose', 'Frugt & Grønt'],
  ['Salat, isbergsalat', 'stk', 'Frugt & Grønt'],
  ['Salat, romainesalat', 'stk', 'Frugt & Grønt'],
  ['Salat, babyleaves', 'pose', 'Frugt & Grønt'],
  ['Kål, hvidkål', 'stk', 'Frugt & Grønt'],
  ['Kål, rødkål', 'stk', 'Frugt & Grønt'],
  ['Kål, spidskål', 'stk', 'Frugt & Grønt'],
  ['Kål, savoykål', 'stk', 'Frugt & Grønt'],
  ['Broccoli', 'stk', 'Frugt & Grønt'],
  ['Blomkål', 'stk', 'Frugt & Grønt'],
  ['Rosenkål', 'pose', 'Frugt & Grønt'],
  ['Grønkål', 'pose', 'Frugt & Grønt'],
  ['Asparges, hvide', 'bundt', 'Frugt & Grønt'],
  ['Asparges, grønne', 'bundt', 'Frugt & Grønt'],
  ['Majs', 'stk', 'Frugt & Grønt'],
  ['Ærter', 'pose', 'Frugt & Grønt'],
  ['Sukkerærter', 'pose', 'Frugt & Grønt'],
  ['Bønner, grønne', 'pose', 'Frugt & Grønt'],
  ['Svampe, champignon', 'bakke', 'Frugt & Grønt'],
  ['Svampe, portobello', 'bakke', 'Frugt & Grønt'],
  ['Svampe, shiitake', 'bakke', 'Frugt & Grønt'],
  ['Svampe, østershatte', 'bakke', 'Frugt & Grønt'],
  ['Persille', 'bundt', 'Frugt & Grønt'],
  ['Dild', 'bundt', 'Frugt & Grønt'],
  ['Basilikum', 'potte', 'Frugt & Grønt'],
  ['Mynte', 'potte', 'Frugt & Grønt'],
  ['Timian', 'potte', 'Frugt & Grønt'],
  ['Rosmarin', 'potte', 'Frugt & Grønt'],
  ['Koriander', 'bundt', 'Frugt & Grønt'],
  ['Frisk ingefær', 'stk', 'Frugt & Grønt'],
  ['Chili, rød', 'stk', 'Frugt & Grønt'],
  ['Chili, grøn', 'stk', 'Frugt & Grønt'],
  ['Fennikel', 'stk', 'Frugt & Grønt'],
  ['Selleri', 'stk', 'Frugt & Grønt'],
  ['Majs på dåse', 'dåse', 'Frugt & Grønt'],
  ['Bambusskud', 'dåse', 'Frugt & Grønt'],
  ['Vandkastanjer', 'dåse', 'Frugt & Grønt'],
  ['Bønnespirer', 'pose', 'Frugt & Grønt'],

  // ── Kød & Fisk ─────────────────────────────────────────────────────
  ['Hakket oksekød 8-12%', 'g', 'Kød & Fisk'],
  ['Hakket oksekød 3-7%', 'g', 'Kød & Fisk'],
  ['Hakket svinekød', 'g', 'Kød & Fisk'],
  ['Hakket kalvekød', 'g', 'Kød & Fisk'],
  ['Hakket lammekød', 'g', 'Kød & Fisk'],
  ['Oksekødsbøf', 'g', 'Kød & Fisk'],
  ['Entrecôte', 'g', 'Kød & Fisk'],
  ['Ribeye', 'g', 'Kød & Fisk'],
  ['Oksemørbrad', 'g', 'Kød & Fisk'],
  ['Okseinderlår', 'g', 'Kød & Fisk'],
  ['Oksebov', 'g', 'Kød & Fisk'],
  ['Oksekæbe', 'g', 'Kød & Fisk'],
  ['Oksehalesuppe', 'g', 'Kød & Fisk'],
  ['Svinemørbrad', 'g', 'Kød & Fisk'],
  ['Svinekoteletter', 'g', 'Kød & Fisk'],
  ['Svinekam', 'g', 'Kød & Fisk'],
  ['Svinebryst', 'g', 'Kød & Fisk'],
  ['Svineribben', 'g', 'Kød & Fisk'],
  ['Flæskesteg', 'g', 'Kød & Fisk'],
  ['Nakkekoteletter', 'g', 'Kød & Fisk'],
  ['Bacon, strimler', 'g', 'Kød & Fisk'],
  ['Bacon, skiver', 'pakke', 'Kød & Fisk'],
  ['Pølser, frankfurterpølser', 'pakke', 'Kød & Fisk'],
  ['Pølser, grillpølser', 'pakke', 'Kød & Fisk'],
  ['Pølser, medisterpølse', 'g', 'Kød & Fisk'],
  ['Pølse, spegepølse', 'pakke', 'Kød & Fisk'],
  ['Leverpostej', 'g', 'Kød & Fisk'],
  ['Rullepølse', 'pakke', 'Kød & Fisk'],
  ['Skinke, kogt', 'pakke', 'Kød & Fisk'],
  ['Skinke, røget', 'pakke', 'Kød & Fisk'],
  ['Salami', 'pakke', 'Kød & Fisk'],
  ['Chorizo', 'pakke', 'Kød & Fisk'],
  ['Lammekølle', 'g', 'Kød & Fisk'],
  ['Lammebov', 'g', 'Kød & Fisk'],
  ['Lammekoteletter', 'g', 'Kød & Fisk'],
  ['Kyllingebryst', 'g', 'Kød & Fisk'],
  ['Kyllingelår', 'g', 'Kød & Fisk'],
  ['Kyllingevinge', 'g', 'Kød & Fisk'],
  ['Kyllingefilet', 'g', 'Kød & Fisk'],
  ['Hel kylling', 'stk', 'Kød & Fisk'],
  ['Kyllingestrimler', 'g', 'Kød & Fisk'],
  ['Kalkun, hakket', 'g', 'Kød & Fisk'],
  ['Kalkun, bryst', 'g', 'Kød & Fisk'],
  ['And, bryst', 'g', 'Kød & Fisk'],
  ['Torsk', 'g', 'Kød & Fisk'],
  ['Laks, filet', 'g', 'Kød & Fisk'],
  ['Laks, røget', 'pakke', 'Kød & Fisk'],
  ['Tun på dåse', 'dåse', 'Kød & Fisk'],
  ['Makrel på dåse', 'dåse', 'Kød & Fisk'],
  ['Sild, marinerede', 'bakke', 'Kød & Fisk'],
  ['Rejer, pillede', 'g', 'Kød & Fisk'],
  ['Rejer, ubehandlede', 'g', 'Kød & Fisk'],
  ['Blæksprutte', 'g', 'Kød & Fisk'],
  ['Muslinger', 'g', 'Kød & Fisk'],
  ['Tilapia', 'g', 'Kød & Fisk'],
  ['Seabass', 'g', 'Kød & Fisk'],
  ['Dorade', 'stk', 'Kød & Fisk'],
  ['Paneret fisk', 'pakke', 'Kød & Fisk'],
  ['Fiskefrikadeller', 'pakke', 'Kød & Fisk'],
  ['Fiskefilet', 'g', 'Kød & Fisk'],
  ['Sej', 'g', 'Kød & Fisk'],
  ['Rødspætte', 'g', 'Kød & Fisk'],
  ['Ansjoser', 'dåse', 'Kød & Fisk'],
  ['Sardiner', 'dåse', 'Kød & Fisk'],

  // ── Mejeri & Æg ────────────────────────────────────────────────────
  ['Sødmælk', 'L', 'Mejeri & Æg'],
  ['Letmælk', 'L', 'Mejeri & Æg'],
  ['Skummetmælk', 'L', 'Mejeri & Æg'],
  ['Kærnemælk', 'L', 'Mejeri & Æg'],
  ['Minimælk', 'L', 'Mejeri & Æg'],
  ['Havremælk', 'L', 'Mejeri & Æg'],
  ['Mandelmælk', 'L', 'Mejeri & Æg'],
  ['Sojamælk', 'L', 'Mejeri & Æg'],
  ['Kokosmælk', 'dåse', 'Mejeri & Æg'],
  ['Fløde 38%', 'dl', 'Mejeri & Æg'],
  ['Piskefløde', 'dl', 'Mejeri & Æg'],
  ['Madlavningsfløde', 'dl', 'Mejeri & Æg'],
  ['Cremefraîche 18%', 'dl', 'Mejeri & Æg'],
  ['Cremefraîche 38%', 'dl', 'Mejeri & Æg'],
  ['Sauerraum', 'dl', 'Mejeri & Æg'],
  ['Smør, usaltet', 'g', 'Mejeri & Æg'],
  ['Smør, saltet', 'g', 'Mejeri & Æg'],
  ['Margarine', 'g', 'Mejeri & Æg'],
  ['Smøreost', 'g', 'Mejeri & Æg'],
  ['Cream cheese', 'g', 'Mejeri & Æg'],
  ['Skyr, naturel', 'g', 'Mejeri & Æg'],
  ['Skyr, vanilje', 'g', 'Mejeri & Æg'],
  ['Yoghurt, naturel', 'g', 'Mejeri & Æg'],
  ['Yoghurt, græsk', 'g', 'Mejeri & Æg'],
  ['Yoghurt, jordbær', 'g', 'Mejeri & Æg'],
  ['Yoghurt, vanilje', 'g', 'Mejeri & Æg'],
  ['Kvark', 'g', 'Mejeri & Æg'],
  ['Hytteost', 'g', 'Mejeri & Æg'],
  ['Ricotta', 'g', 'Mejeri & Æg'],
  ['Mascarpone', 'g', 'Mejeri & Æg'],
  ['Ost, danbo 30+', 'g', 'Mejeri & Æg'],
  ['Ost, danbo 45+', 'g', 'Mejeri & Æg'],
  ['Ost, emmentaler', 'g', 'Mejeri & Æg'],
  ['Ost, gouda', 'g', 'Mejeri & Æg'],
  ['Ost, cheddar', 'g', 'Mejeri & Æg'],
  ['Ost, brie', 'g', 'Mejeri & Æg'],
  ['Ost, camembert', 'stk', 'Mejeri & Æg'],
  ['Ost, gorgonzola', 'g', 'Mejeri & Æg'],
  ['Ost, parmesan', 'g', 'Mejeri & Æg'],
  ['Ost, mozzarella', 'g', 'Mejeri & Æg'],
  ['Ost, feta', 'g', 'Mejeri & Æg'],
  ['Ost, halloumi', 'g', 'Mejeri & Æg'],
  ['Ost, manchego', 'g', 'Mejeri & Æg'],
  ['Ost, gruyère', 'g', 'Mejeri & Æg'],
  ['Ost, blåskimmel', 'g', 'Mejeri & Æg'],
  ['Ost, röd ledar', 'g', 'Mejeri & Æg'],
  ['Ost, revet blanding', 'g', 'Mejeri & Æg'],
  ['Æg, 6-pak', 'pakke', 'Mejeri & Æg'],
  ['Æg, 10-pak', 'pakke', 'Mejeri & Æg'],
  ['Æg, 15-pak', 'pakke', 'Mejeri & Æg'],
  ['Is, vanilje', 'L', 'Mejeri & Æg'],
  ['Is, chokolade', 'L', 'Mejeri & Æg'],
  ['Fraîcheur', 'g', 'Mejeri & Æg'],

  // ── Brød & Bageri ──────────────────────────────────────────────────
  ['Rugbrød', 'stk', 'Brød & Bageri'],
  ['Franskbrød', 'stk', 'Brød & Bageri'],
  ['Fuldkornsbrød', 'stk', 'Brød & Bageri'],
  ['Surdejsbrød', 'stk', 'Brød & Bageri'],
  ['Flutes', 'stk', 'Brød & Bageri'],
  ['Ciabatta', 'stk', 'Brød & Bageri'],
  ['Toastbrød', 'pakke', 'Brød & Bageri'],
  ['Burgerboller', 'pakke', 'Brød & Bageri'],
  ['Hotdogbrød', 'pakke', 'Brød & Bageri'],
  ['Pitabrød', 'pakke', 'Brød & Bageri'],
  ['Tortillas', 'pakke', 'Brød & Bageri'],
  ['Knækbrød', 'pakke', 'Brød & Bageri'],
  ['Riskagemadder', 'pakke', 'Brød & Bageri'],
  ['Riskager', 'pakke', 'Brød & Bageri'],
  ['Croissant', 'stk', 'Brød & Bageri'],
  ['Kanelsnegl', 'stk', 'Brød & Bageri'],
  ['Rundstykke', 'stk', 'Brød & Bageri'],
  ['Morgenbrød', 'stk', 'Brød & Bageri'],
  ['Focaccia', 'stk', 'Brød & Bageri'],
  ['Naan', 'pakke', 'Brød & Bageri'],
  ['Bagel', 'stk', 'Brød & Bageri'],
  ['Wraps', 'pakke', 'Brød & Bageri'],
  ['Kiks, digestive', 'pakke', 'Brød & Bageri'],
  ['Kiks, water crackers', 'pakke', 'Brød & Bageri'],
  ['Kiks, havre', 'pakke', 'Brød & Bageri'],
  ['Müslibarer', 'pakke', 'Brød & Bageri'],
  ['Franskbrødsmel', 'kg', 'Brød & Bageri'],
  ['Mel, hvedemel', 'kg', 'Brød & Bageri'],
  ['Mel, rugmel', 'kg', 'Brød & Bageri'],
  ['Mel, fuldkornsmel', 'kg', 'Brød & Bageri'],
  ['Mel, rismel', 'kg', 'Brød & Bageri'],
  ['Gær, frisk', 'g', 'Brød & Bageri'],
  ['Gær, tørgær', 'pakke', 'Brød & Bageri'],
  ['Bagepulver', 'pakke', 'Brød & Bageri'],
  ['Natron', 'pakke', 'Brød & Bageri'],
  ['Kagecreme', 'pakke', 'Brød & Bageri'],
  ['Tortillachips', 'pose', 'Brød & Bageri'],

  // ── Kolonial ────────────────────────────────────────────────────────
  ['Pasta, spaghetti', 'g', 'Kolonial'],
  ['Pasta, penne', 'g', 'Kolonial'],
  ['Pasta, fusilli', 'g', 'Kolonial'],
  ['Pasta, tagliatelle', 'g', 'Kolonial'],
  ['Pasta, lasagneplader', 'pakke', 'Kolonial'],
  ['Pasta, rigatoni', 'g', 'Kolonial'],
  ['Pasta, farfalle', 'g', 'Kolonial'],
  ['Pasta, linguine', 'g', 'Kolonial'],
  ['Pasta, orzo', 'g', 'Kolonial'],
  ['Ris, basmati', 'g', 'Kolonial'],
  ['Ris, jasmin', 'g', 'Kolonial'],
  ['Ris, grødris', 'g', 'Kolonial'],
  ['Ris, fuldkornsris', 'g', 'Kolonial'],
  ['Ris, risotto', 'g', 'Kolonial'],
  ['Couscous', 'g', 'Kolonial'],
  ['Bulgur', 'g', 'Kolonial'],
  ['Quinoa', 'g', 'Kolonial'],
  ['Polenta', 'g', 'Kolonial'],
  ['Havregryn', 'g', 'Kolonial'],
  ['Havregryn, grove', 'g', 'Kolonial'],
  ['Cornflakes', 'g', 'Kolonial'],
  ['Müsli', 'g', 'Kolonial'],
  ['Grød, havregrød', 'pose', 'Kolonial'],
  ['Linser, røde', 'g', 'Kolonial'],
  ['Linser, grønne', 'g', 'Kolonial'],
  ['Kikærter, tørre', 'g', 'Kolonial'],
  ['Kikærter, dåse', 'dåse', 'Kolonial'],
  ['Hvide bønner, dåse', 'dåse', 'Kolonial'],
  ['Sorte bønner, dåse', 'dåse', 'Kolonial'],
  ['Kidneybønner, dåse', 'dåse', 'Kolonial'],
  ['Blandede bønner, dåse', 'dåse', 'Kolonial'],
  ['Hakkede tomater, dåse', 'dåse', 'Kolonial'],
  ['Flåede tomater, dåse', 'dåse', 'Kolonial'],
  ['Tomatpuré', 'dåse', 'Kolonial'],
  ['Tomatsauce, basilikum', 'dåse', 'Kolonial'],
  ['Tomatsauce, arrabbiata', 'dåse', 'Kolonial'],
  ['Passata', 'L', 'Kolonial'],
  ['Olivenolie, ekstra jomfru', 'dl', 'Kolonial'],
  ['Olivenolie', 'dl', 'Kolonial'],
  ['Rapsolie', 'dl', 'Kolonial'],
  ['Solsikkeolie', 'dl', 'Kolonial'],
  ['Kokosolie', 'g', 'Kolonial'],
  ['Sesamolie', 'dl', 'Kolonial'],
  ['Vindruekerneolie', 'dl', 'Kolonial'],
  ['Eddike, alm.', 'dl', 'Kolonial'],
  ['Eddike, æble', 'dl', 'Kolonial'],
  ['Eddike, balsamico', 'dl', 'Kolonial'],
  ['Eddike, ris', 'dl', 'Kolonial'],
  ['Sojasauce', 'dl', 'Kolonial'],
  ['Fiskesauce', 'dl', 'Kolonial'],
  ['Worcestershiresauce', 'dl', 'Kolonial'],
  ['Tabasco', 'dl', 'Kolonial'],
  ['Sriracha', 'dl', 'Kolonial'],
  ['Hoisinsauce', 'dl', 'Kolonial'],
  ['Teriyakisauce', 'dl', 'Kolonial'],
  ['Ketjap manis', 'dl', 'Kolonial'],
  ['Oyster sauce', 'dl', 'Kolonial'],
  ['Ketchup', 'dl', 'Kolonial'],
  ['Sennep, grov', 'g', 'Kolonial'],
  ['Sennep, dijon', 'g', 'Kolonial'],
  ['Sennep, alm.', 'g', 'Kolonial'],
  ['Mayonnaise', 'g', 'Kolonial'],
  ['Remoulade', 'g', 'Kolonial'],
  ['Aioli', 'g', 'Kolonial'],
  ['Bbq-sauce', 'dl', 'Kolonial'],
  ['Chilisauce, sød', 'dl', 'Kolonial'],
  ['Pesto, grøn', 'g', 'Kolonial'],
  ['Pesto, rød', 'g', 'Kolonial'],
  ['Hummus', 'g', 'Kolonial'],
  ['Tahin', 'g', 'Kolonial'],
  ['Jordnøddesmør', 'g', 'Kolonial'],
  ['Syltetøj, jordbær', 'g', 'Kolonial'],
  ['Syltetøj, hindbær', 'g', 'Kolonial'],
  ['Marmelade, appelsin', 'g', 'Kolonial'],
  ['Honning', 'g', 'Kolonial'],
  ['Ahornsirup', 'dl', 'Kolonial'],
  ['Sukker, hvidt', 'g', 'Kolonial'],
  ['Sukker, brunt', 'g', 'Kolonial'],
  ['Flormelis', 'g', 'Kolonial'],
  ['Rørsukker', 'g', 'Kolonial'],
  ['Stevia', 'pakke', 'Kolonial'],
  ['Vanilje, stang', 'stk', 'Kolonial'],
  ['Vaniljesukker', 'pakke', 'Kolonial'],
  ['Chokolade, mørk 70%', 'g', 'Kolonial'],
  ['Chokolade, mørk 85%', 'g', 'Kolonial'],
  ['Chokolade, lys', 'g', 'Kolonial'],
  ['Chokolade, hvid', 'g', 'Kolonial'],
  ['Kakaopulver', 'g', 'Kolonial'],
  ['Nødder, mandler', 'g', 'Kolonial'],
  ['Nødder, cashewnødder', 'g', 'Kolonial'],
  ['Nødder, valnødder', 'g', 'Kolonial'],
  ['Nødder, hasselnødder', 'g', 'Kolonial'],
  ['Nødder, pistacienødder', 'g', 'Kolonial'],
  ['Nødder, pinjekerner', 'g', 'Kolonial'],
  ['Nødder, peanuts', 'g', 'Kolonial'],
  ['Nødder, macadamia', 'g', 'Kolonial'],
  ['Mandler, flager', 'g', 'Kolonial'],
  ['Mandler, malede', 'g', 'Kolonial'],
  ['Sesamfrø', 'g', 'Kolonial'],
  ['Chiafrø', 'g', 'Kolonial'],
  ['Hørfrø', 'g', 'Kolonial'],
  ['Solsikkefrø', 'g', 'Kolonial'],
  ['Græskarkerner', 'g', 'Kolonial'],
  ['Rosiner', 'g', 'Kolonial'],
  ['Tørrede tranebær', 'g', 'Kolonial'],
  ['Dadler', 'g', 'Kolonial'],
  ['Tørrede abrikoser', 'g', 'Kolonial'],
  ['Tørrede figner', 'g', 'Kolonial'],
  ['Salt', 'g', 'Kolonial'],
  ['Havsalt', 'g', 'Kolonial'],
  ['Flagesalt', 'g', 'Kolonial'],
  ['Peber, sort hel', 'g', 'Kolonial'],
  ['Peber, sort malet', 'g', 'Kolonial'],
  ['Peber, hvid', 'g', 'Kolonial'],
  ['Peber, cayenne', 'g', 'Kolonial'],
  ['Paprika, sød', 'g', 'Kolonial'],
  ['Paprika, røget', 'g', 'Kolonial'],
  ['Spidskommen', 'g', 'Kolonial'],
  ['Koriander, malet', 'g', 'Kolonial'],
  ['Karry', 'g', 'Kolonial'],
  ['Gurkemeje', 'g', 'Kolonial'],
  ['Kanel', 'g', 'Kolonial'],
  ['Muskatnød', 'stk', 'Kolonial'],
  ['Nelliker', 'g', 'Kolonial'],
  ['Allehånde', 'g', 'Kolonial'],
  ['Stjerneanis', 'g', 'Kolonial'],
  ['Kardemomme', 'g', 'Kolonial'],
  ['Ingefær, tørret', 'g', 'Kolonial'],
  ['Laurbærblade', 'g', 'Kolonial'],
  ['Oregano, tørret', 'g', 'Kolonial'],
  ['Basilikum, tørret', 'g', 'Kolonial'],
  ['Timian, tørret', 'g', 'Kolonial'],
  ['Rosmarin, tørret', 'g', 'Kolonial'],
  ['Dild, tørret', 'g', 'Kolonial'],
  ['Persille, tørret', 'g', 'Kolonial'],
  ['Hvidløgspulver', 'g', 'Kolonial'],
  ['Løgpulver', 'g', 'Kolonial'],
  ['Chiliflager', 'g', 'Kolonial'],
  ['Garam masala', 'g', 'Kolonial'],
  ['Ras el hanout', 'g', 'Kolonial'],
  ['Tandoorikrydderi', 'g', 'Kolonial'],
  ['Bouillon, okse', 'stk', 'Kolonial'],
  ['Bouillon, kylling', 'stk', 'Kolonial'],
  ['Bouillon, grøntsag', 'stk', 'Kolonial'],
  ['Bouillon, fisk', 'stk', 'Kolonial'],
  ['Bouillonpasta, okse', 'g', 'Kolonial'],
  ['Fond, kalv', 'dl', 'Kolonial'],
  ['Fond, kylling', 'dl', 'Kolonial'],
  ['Maizena', 'g', 'Kolonial'],
  ['Sovsejævner', 'g', 'Kolonial'],
  ['Gelatineblade', 'pakke', 'Kolonial'],
  ['Agar agar', 'g', 'Kolonial'],
  ['Kokosmælk, light', 'dåse', 'Kolonial'],
  ['Kokosfløde', 'dåse', 'Kolonial'],
  ['Tofu, fast', 'g', 'Kolonial'],
  ['Tofu, silke', 'g', 'Kolonial'],
  ['Tempeh', 'g', 'Kolonial'],
  ['Seitan', 'g', 'Kolonial'],
  ['Nudler, risnudler', 'g', 'Kolonial'],
  ['Nudler, æggenudler', 'g', 'Kolonial'],
  ['Nudler, glasnudler', 'g', 'Kolonial'],
  ['Nudler, ramen', 'pakke', 'Kolonial'],
  ['Panko, rasp', 'g', 'Kolonial'],
  ['Rasp', 'g', 'Kolonial'],
  ['Oliven, sorte', 'g', 'Kolonial'],
  ['Oliven, grønne', 'g', 'Kolonial'],
  ['Kapers', 'g', 'Kolonial'],
  ['Syltede agurker', 'g', 'Kolonial'],
  ['Syltet rødkål', 'g', 'Kolonial'],
  ['Sauerkraut', 'g', 'Kolonial'],
  ['Chipotlepasta', 'g', 'Kolonial'],
  ['Harissapasta', 'g', 'Kolonial'],
  ['Tahini', 'g', 'Kolonial'],
  ['Miso, hvid', 'g', 'Kolonial'],
  ['Miso, rød', 'g', 'Kolonial'],
  ['Wasabi', 'g', 'Kolonial'],
  ['Ingefær, syltede', 'g', 'Kolonial'],
  ['Kokosmel', 'g', 'Kolonial'],
  ['Kokosspåner', 'g', 'Kolonial'],
  ['Chipotlesauce', 'dl', 'Kolonial'],
  ['Sambal oelek', 'g', 'Kolonial'],
  ['Citrongræs, tørret', 'g', 'Kolonial'],
  ['Galangal, tørret', 'g', 'Kolonial'],
  ['Tomatsuppe, dåse', 'dåse', 'Kolonial'],
  ['Linsesuppe, dåse', 'dåse', 'Kolonial'],

  // ── Frost ──────────────────────────────────────────────────────────
  ['Frosne ærter', 'g', 'Frost'],
  ['Froset majs', 'g', 'Frost'],
  ['Frosne blandede grøntsager', 'g', 'Frost'],
  ['Frosne broccoli', 'g', 'Frost'],
  ['Frosne spinat', 'g', 'Frost'],
  ['Frosne bønner, grønne', 'g', 'Frost'],
  ['Frosne rosenkål', 'g', 'Frost'],
  ['Frosne blåbær', 'g', 'Frost'],
  ['Frosne hindbær', 'g', 'Frost'],
  ['Frosne jordbær', 'g', 'Frost'],
  ['Frosne blandede bær', 'g', 'Frost'],
  ['Frosne mango', 'g', 'Frost'],
  ['Frossen laks', 'g', 'Frost'],
  ['Frosne rejer', 'g', 'Frost'],
  ['Frosne fiskefileter', 'g', 'Frost'],
  ['Frosne kyllingefileter', 'g', 'Frost'],
  ['Frosne kyllingelår', 'g', 'Frost'],
  ['Frossen hakket oksekød', 'g', 'Frost'],
  ['Frosne frikadeller', 'stk', 'Frost'],
  ['Frosne pølser', 'g', 'Frost'],
  ['Frossen pizza, margherita', 'stk', 'Frost'],
  ['Frossen pizza, pepperoni', 'stk', 'Frost'],
  ['Frossen lasagne', 'g', 'Frost'],
  ['Frossen pitabrød', 'pakke', 'Frost'],
  ['Frossen smørbrødsdej', 'pakke', 'Frost'],
  ['Frossen butterdej', 'pakke', 'Frost'],
  ['Frossen mørdej', 'pakke', 'Frost'],
  ['Frossen kartoffelbåde', 'g', 'Frost'],
  ['Frossen pommes frites', 'g', 'Frost'],
  ['Frossen hashbrown', 'g', 'Frost'],
  ['Is, vanilje (frost)', 'L', 'Frost'],
  ['Is, chokolade (frost)', 'L', 'Frost'],
  ['Frossen flødeboller', 'pakke', 'Frost'],
  ['Frossen æbletærte', 'stk', 'Frost'],
  ['Frossen cookie dough', 'g', 'Frost'],
  ['Edamame, frosne', 'g', 'Frost'],

  // ── Drikkevarer ────────────────────────────────────────────────────
  ['Vand, danskvand', 'L', 'Drikkevarer'],
  ['Vand, stille', 'L', 'Drikkevarer'],
  ['Sodavand, cola', 'L', 'Drikkevarer'],
  ['Sodavand, cola light', 'L', 'Drikkevarer'],
  ['Sodavand, appelsin', 'L', 'Drikkevarer'],
  ['Sodavand, citron', 'L', 'Drikkevarer'],
  ['Sodavand, cola zero', 'L', 'Drikkevarer'],
  ['Energidrik', 'stk', 'Drikkevarer'],
  ['Juice, appelsinjuice', 'L', 'Drikkevarer'],
  ['Juice, æblejuice', 'L', 'Drikkevarer'],
  ['Juice, multivitamin', 'L', 'Drikkevarer'],
  ['Juice, grapefrugt', 'L', 'Drikkevarer'],
  ['Juice, mango', 'L', 'Drikkevarer'],
  ['Juice, tomat', 'L', 'Drikkevarer'],
  ['Smoothie', 'stk', 'Drikkevarer'],
  ['Kaffe, helbønner', 'g', 'Drikkevarer'],
  ['Kaffe, malet', 'g', 'Drikkevarer'],
  ['Kaffe, instant', 'g', 'Drikkevarer'],
  ['Kaffe, kapsler', 'pakke', 'Drikkevarer'],
  ['Te, sort', 'pakke', 'Drikkevarer'],
  ['Te, grøn', 'pakke', 'Drikkevarer'],
  ['Te, urtete', 'pakke', 'Drikkevarer'],
  ['Te, ingefær citron', 'pakke', 'Drikkevarer'],
  ['Kakao, drikkechokolade', 'g', 'Drikkevarer'],
  ['Vin, rødvin', 'L', 'Drikkevarer'],
  ['Vin, hvidvin', 'L', 'Drikkevarer'],
  ['Vin, rosévin', 'L', 'Drikkevarer'],
  ['Øl, pilsner', 'stk', 'Drikkevarer'],
  ['Øl, IPA', 'stk', 'Drikkevarer'],
  ['Øl, mørk', 'stk', 'Drikkevarer'],
  ['Øl, alkoholfri', 'stk', 'Drikkevarer'],
  ['Cider', 'stk', 'Drikkevarer'],
  ['Prosecco', 'stk', 'Drikkevarer'],
  ['Sportsdrik', 'stk', 'Drikkevarer'],
  ['Proteinshake', 'stk', 'Drikkevarer'],
  ['Havredrik', 'L', 'Drikkevarer'],
  ['Lemonade', 'L', 'Drikkevarer'],
  ['Iste', 'L', 'Drikkevarer'],

  // ── Husholdning ────────────────────────────────────────────────────
  ['Opvaskemiddel', 'stk', 'Husholdning'],
  ['Opvaskemiddelkapsler', 'pakke', 'Husholdning'],
  ['Skyllemiddel, opvaskemaskine', 'stk', 'Husholdning'],
  ['Afkalkningsmiddel, opvaskemaskine', 'stk', 'Husholdning'],
  ['Vaskepulver', 'g', 'Husholdning'],
  ['Flydende vaskemiddel', 'L', 'Husholdning'],
  ['Vaskekapsler', 'pakke', 'Husholdning'],
  ['Skyllemiddel, tøj', 'L', 'Husholdning'],
  ['Rengøringsmiddel, universalspray', 'stk', 'Husholdning'],
  ['Rengøringsmiddel, badeværelse', 'stk', 'Husholdning'],
  ['Rengøringsmiddel, toilet', 'stk', 'Husholdning'],
  ['Rengøringsmiddel, gulv', 'L', 'Husholdning'],
  ['Rengøringsmiddel, vindue', 'stk', 'Husholdning'],
  ['Rengøringsmiddel, ovn', 'stk', 'Husholdning'],
  ['Affaldssække, store', 'pakke', 'Husholdning'],
  ['Affaldssække, små', 'pakke', 'Husholdning'],
  ['Køkkenrulle', 'pakke', 'Husholdning'],
  ['Toiletpapir', 'pakke', 'Husholdning'],
  ['Næsepapir', 'pakke', 'Husholdning'],
  ['Køkkenservietter', 'pakke', 'Husholdning'],
  ['Husholdningsfilm', 'stk', 'Husholdning'],
  ['Aluminiumsfolie', 'stk', 'Husholdning'],
  ['Bagepapir', 'stk', 'Husholdning'],
  ['Fryseposer', 'pakke', 'Husholdning'],
  ['Lynlåsposer', 'pakke', 'Husholdning'],
  ['Stegeposeruller', 'pakke', 'Husholdning'],
  ['Tandbørste', 'stk', 'Husholdning'],
  ['Tandpasta', 'stk', 'Husholdning'],
  ['Tandtråd', 'stk', 'Husholdning'],
  ['Mundskyl', 'stk', 'Husholdning'],
  ['Shampoo', 'stk', 'Husholdning'],
  ['Balsam', 'stk', 'Husholdning'],
  ['Håndkøb, sæbe', 'stk', 'Husholdning'],
  ['Bodylotion', 'stk', 'Husholdning'],
  ['Deodorant', 'stk', 'Husholdning'],
  ['Barberskum', 'stk', 'Husholdning'],
  ['Barberblade', 'pakke', 'Husholdning'],
  ['Vatpinde', 'pakke', 'Husholdning'],
  ['Vatpuder', 'pakke', 'Husholdning'],
  ['Menstruationsbind', 'pakke', 'Husholdning'],
  ['Tamponer', 'pakke', 'Husholdning'],
  ['Bleer', 'pakke', 'Husholdning'],
  ['Vådservietter', 'pakke', 'Husholdning'],
  ['Hånddesinfektionsmiddel', 'stk', 'Husholdning'],
  ['Plaster', 'pakke', 'Husholdning'],
  ['Ibuprofen', 'pakke', 'Husholdning'],
  ['Paracetamol', 'pakke', 'Husholdning'],
  ['Hundegodter', 'pose', 'Husholdning'],
  ['Kattegodter', 'pose', 'Husholdning'],
  ['Dyrefoder, hund', 'pose', 'Husholdning'],
  ['Dyrefoder, kat', 'pose', 'Husholdning'],
  ['Batterier, AA', 'pakke', 'Husholdning'],
  ['Batterier, AAA', 'pakke', 'Husholdning'],
  ['Lightere', 'stk', 'Husholdning'],
  ['Tændstikker', 'pakke', 'Husholdning'],
  ['Stearinlys', 'stk', 'Husholdning'],

];

const insert = db.prepare(
  'INSERT OR IGNORE INTO products (name, default_unit, shop_category) VALUES (?, ?, ?)'
);

let inserted = 0;
let skipped  = 0;

for (const [name, unit, cat] of products) {
  const changes = insert.run(name, unit, cat).changes;
  if (changes) inserted++; else skipped++;
}

console.log(`✓ Indsatte ${inserted} produkter. Sprang ${skipped} over (fandtes allerede).`);
